/**
 * Best-effort "what does this word look like" lookup, used to show a small
 * illustrative emoji next to a kanji/vocabulary answer once it's revealed.
 *
 * There's no offline/local source of real photography for ~1300 course
 * items, so this maps concrete English glosses to a representative emoji
 * instead. Coverage is intentionally partial: abstract words, particles and
 * grammar-only entries return undefined, and callers should render nothing
 * in that case rather than force an unrelated picture.
 */
import type { LocalizedText } from "../../data/types";

// Keys are normalized (lowercase, no punctuation) English phrases. Multi-word
// keys are checked before single-word ones so "older sister" wins over "sister".
const ILLUSTRATIONS: Record<string, string> = {
  // People & family
  "person": "🧑",
  "human being": "🧑",
  "man": "👨",
  "woman": "👩",
  "boy": "👦",
  "girl": "👧",
  "child": "🧒",
  "children": "🧒",
  "baby": "👶",
  "friend": "🧑‍🤝‍🧑",
  "family": "👨‍👩‍👧‍👦",
  "father": "👨",
  "mother": "👩",
  "dad": "👨",
  "mom": "👩",
  "older brother": "👦",
  "older sister": "👧",
  "younger brother": "🧒",
  "younger sister": "🧒",
  "grandfather": "👴",
  "grandmother": "👵",
  "husband": "🤵",
  "wife": "👰",
  "teacher": "🧑‍🏫",
  "student": "🎓",
  "doctor": "🧑‍⚕️",
  "name": "🪪",

  // Numbers
  "one": "1️⃣",
  "two": "2️⃣",
  "three": "3️⃣",
  "four": "4️⃣",
  "five": "5️⃣",
  "six": "6️⃣",
  "seven": "7️⃣",
  "eight": "8️⃣",
  "nine": "9️⃣",
  "ten": "🔟",
  "one hundred": "💯",
  "one thousand": "🔢",
  "ten thousand": "🔢",
  "zero": "0️⃣",

  // Time
  "today": "📅",
  "tomorrow": "📅",
  "yesterday": "📅",
  "morning": "🌅",
  "noon": "🕛",
  "afternoon": "🌇",
  "evening": "🌆",
  "night": "🌙",
  "week": "📆",
  "month": "🗓️",
  "year": "📅",
  "time": "🕐",
  "hour": "⏰",
  "minute": "⏱️",
  "monday": "📅",
  "tuesday": "📅",
  "wednesday": "📅",
  "thursday": "📅",
  "friday": "📅",
  "saturday": "📅",
  "sunday": "📅",

  // Countries / nationalities / languages
  "japan": "🇯🇵",
  "japanese": "🇯🇵",
  "china": "🇨🇳",
  "chinese": "🇨🇳",
  "south korea": "🇰🇷",
  "korean": "🇰🇷",
  "america": "🇺🇸",
  "american": "🇺🇸",
  "usa": "🇺🇸",
  "russia": "🇷🇺",
  "russian": "🇷🇺",
  "france": "🇫🇷",
  "french": "🇫🇷",
  "united kingdom": "🇬🇧",
  "british": "🇬🇧",
  "spain": "🇪🇸",
  "spanish": "🇪🇸",
  "germany": "🇩🇪",
  "german": "🇩🇪",
  "belgium": "🇧🇪",
  "belgian": "🇧🇪",
  "italy": "🇮🇹",
  "italian": "🇮🇹",

  // Animals
  "dog": "🐕",
  "cat": "🐈",
  "bird": "🐦",
  "fish": "🐟",
  "horse": "🐴",
  "cow": "🐄",
  "pig": "🐖",
  "chicken": "🐔",
  "rabbit": "🐇",
  "mouse": "🐁",
  "insect": "🐛",
  "snake": "🐍",
  "tiger": "🐯",
  "elephant": "🐘",
  "monkey": "🐒",
  "bear": "🐻",
  "lion": "🦁",
  "sheep": "🐑",
  "frog": "🐸",
  "turtle": "🐢",
  "butterfly": "🦋",

  // Food & drink
  "rice": "🍚",
  "bread": "🍞",
  "meat": "🥩",
  "egg": "🥚",
  "vegetable": "🥦",
  "fruit": "🍎",
  "apple": "🍎",
  "orange": "🍊",
  "banana": "🍌",
  "tea": "🍵",
  "coffee": "☕",
  "water": "💧",
  "milk": "🥛",
  "sushi": "🍣",
  "noodle": "🍜",
  "soup": "🍲",
  "cake": "🍰",
  "candy": "🍬",
  "chocolate": "🍫",
  "beer": "🍺",
  "wine": "🍷",
  "sugar": "🍬",
  "salt": "🧂",

  // Body
  "head": "🧠",
  "eye": "👁️",
  "ear": "👂",
  "nose": "👃",
  "mouth": "👄",
  "hand": "✋",
  "foot": "🦶",
  "hair": "💇",
  "tooth": "🦷",
  "heart": "❤️",
  "face": "😊",

  // House / places
  "house": "🏠",
  "home": "🏠",
  "room": "🚪",
  "door": "🚪",
  "window": "🪟",
  "table": "🪑",
  "chair": "🪑",
  "bed": "🛏️",
  "bath": "🛁",
  "kitchen": "🍳",
  "garden": "🌳",
  "key": "🔑",
  "phone": "📱",
  "television": "📺",
  "computer": "💻",
  "camera": "📷",
  "clock": "🕐",
  "umbrella": "☂️",
  "glasses": "👓",
  "watch": "⌚",
  "bag": "🎒",
  "wallet": "👛",
  "money": "💰",
  "ticket": "🎫",
  "school": "🏫",
  "hospital": "🏥",
  "bank": "🏦",
  "post office": "📮",
  "library": "📚",
  "museum": "🏛️",
  "park": "🌳",
  "beach": "🏖️",
  "mountain": "⛰️",
  "city": "🏙️",
  "country": "🌍",
  "hotel": "🏨",
  "restaurant": "🍽️",
  "cafe": "☕",
  "shop": "🏪",
  "store": "🏪",
  "supermarket": "🛒",
  "station": "🚉",
  "airport": "✈️",
  "company": "🏢",
  "office": "🏢",
  "book": "📖",
  "dictionary": "📕",
  "pen": "🖊️",
  "pencil": "✏️",
  "desk": "🪑",
  "test": "📝",
  "homework": "📝",
  "letter": "✉️",
  "newspaper": "📰",
  "map": "🗺️",

  // Transportation
  "car": "🚗",
  "train": "🚃",
  "bicycle": "🚲",
  "airplane": "✈️",
  "bus": "🚌",
  "ship": "🚢",
  "taxi": "🚕",
  "subway": "🚇",
  "road": "🛣️",
  "bridge": "🌉",

  // Nature / weather
  "sun": "☀️",
  "moon": "🌙",
  "star": "⭐",
  "rain": "🌧️",
  "snow": "❄️",
  "wind": "💨",
  "cloud": "☁️",
  "sky": "🌤️",
  "river": "🏞️",
  "sea": "🌊",
  "ocean": "🌊",
  "tree": "🌳",
  "flower": "🌸",
  "leaf": "🍃",
  "fire": "🔥",
  "ice": "🧊",
  "sand": "🏖️",
  "stone": "🪨",
  "earth": "🌍",
  "weather": "⛅",

  // Colors
  "red": "🔴",
  "blue": "🔵",
  "yellow": "🟡",
  "green": "🟢",
  "white": "⚪",
  "black": "⚫",
  "brown": "🟤",
  "purple": "🟣",
  "pink": "🌸",
  "orange color": "🟠",
  "gray": "⚪",
  "grey": "⚪",
  "color": "🎨",

  // Common verbs
  "eat": "🍽️",
  "drink": "🥤",
  "sleep": "😴",
  "read": "📖",
  "write": "✍️",
  "speak": "💬",
  "talk": "💬",
  "listen": "👂",
  "hear": "👂",
  "see": "👀",
  "look": "👀",
  "go": "🚶",
  "come": "🚶",
  "buy": "🛒",
  "sell": "🏷️",
  "study": "📚",
  "learn": "📚",
  "teach": "🧑‍🏫",
  "work": "💼",
  "play": "🎮",
  "swim": "🏊",
  "run": "🏃",
  "walk": "🚶",
  "sing": "🎤",
  "dance": "💃",
  "cook": "🍳",
  "wash": "🧼",
  "open": "🔓",
  "close": "🔒",
  "stand": "🧍",
  "sit": "🪑",
  "wait": "⏳",
  "wear": "👕",
  "help": "🤝",
  "meet": "🤝",
  "know": "💡",
  "think": "💭",
  "love": "❤️",
  "like": "👍",
  "want": "🙏",
  "give": "🎁",
  "make": "🛠️",
  "use": "🔧",
  "live": "🏠",
  "die": "⚰️",
  "smoke": "🚬",
  "call": "📞",
  "return": "↩️",
  "borrow": "🤲",
  "lend": "🤲",
  "travel": "🧳",
  "drive": "🚗",
  "fly": "✈️",
  "rest": "🛋️",
  "enter": "🚪",
  "leave": "🚪",
  "arrive": "🏁",
  "start": "▶️",
  "finish": "🏁",
  "practice": "🏋️",

  // Common adjectives
  "big": "🐘",
  "large": "🐘",
  "small": "🐭",
  "little": "🐭",
  "hot": "🔥",
  "cold": "🧊",
  "new": "✨",
  "old": "🕰️",
  "expensive": "💰",
  "cheap": "🪙",
  "delicious": "😋",
  "tasty": "😋",
  "beautiful": "🌸",
  "pretty": "🌸",
  "fun": "🎉",
  "interesting": "🤔",
  "boring": "😑",
  "busy": "🏃",
  "tired": "😩",
  "happy": "😊",
  "sad": "😢",
  "angry": "😠",
  "scared": "😨",
  "afraid": "😨",
  "easy": "🙂",
  "difficult": "😖",
  "hard": "😖",
  "fast": "⚡",
  "slow": "🐌",
  "long": "📏",
  "short": "📏",
  "high": "⬆️",
  "low": "⬇️",
  "heavy": "🏋️",
  "light": "🪶",
  "strong": "💪",
  "weak": "🦴",
  "quiet": "🤫",
  "noisy": "🔊",
  "clean": "✨",
  "dirty": "🧹",
  "kind": "😊",
  "good": "👍",
  "bad": "👎",
  "many": "🔢",
  "few": "🔢",

  // Sports / hobbies
  "sport": "⚽",
  "soccer": "⚽",
  "baseball": "⚾",
  "tennis": "🎾",
  "music": "🎵",
  "movie": "🎬",
  "photograph": "📷",
  "picture": "🖼️",
  "game": "🎮",
  "party": "🎉",
  "festival": "🎏",
  "trip": "🧳",
  "vacation": "🏖️",

  // Extra coverage: pronouns, months, position words, misc common glosses
  "i": "🙋",
  "me": "🙋",
  "he": "👨",
  "she": "👩",
  "you": "🫵",
  "everyone": "👥",
  "people": "👥",
  "adult": "🧑",
  "january": "📅",
  "february": "📅",
  "march": "📅",
  "april": "📅",
  "may": "📅",
  "june": "📅",
  "july": "📅",
  "august": "📅",
  "september": "📅",
  "october": "📅",
  "november": "📅",
  "december": "📅",
  "weekday": "📅",
  "yen": "💴",
  "gold": "🥇",
  "soil": "🌱",
  "gate": "⛩️",
  "shrine": "⛩️",
  "temple": "🛕",
  "sword": "🗡️",
  "knife": "🔪",
  "life": "👶",
  "birth": "👶",
  "body": "🧍",
  "now": "⏰",
  "before": "⏪",
  "front": "⏪",
  "previous": "⏪",
  "earlier": "⏪",
  "behind": "⏩",
  "back": "⏩",
  "later": "⏩",
  "up": "⬆️",
  "above": "⬆️",
  "upper": "⬆️",
  "down": "⬇️",
  "below": "⬇️",
  "lower": "⬇️",
  "decrease": "📉",
  "increase": "📈",
  "raw": "🥩",
  "bright": "💡",
  "pizza": "🍕",
};

// Sorted once, longest phrase first, so multi-word keys win over their
// single-word substrings (e.g. "older sister" before "sister").
const SORTED_KEYS = Object.keys(ILLUSTRATIONS).sort((a, b) => b.length - a.length);

function normalize(text: string): string {
  return text
    .toLowerCase()
    .replace(/\([^)]*\)/g, " ")
    .replace(/\[[^\]]*\]/g, " ")
    .replace(/[^a-z\s'-]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function findInPhrase(phrase: string): string | undefined {
  if (!phrase) return undefined;
  for (const key of SORTED_KEYS) {
    const re = new RegExp(`(?:^|\\s)${key}(?:$|\\s)`);
    if (re.test(phrase)) return ILLUSTRATIONS[key];
  }
  return undefined;
}

/** Returns a representative emoji for the item's meaning, or undefined if none applies. */
export function illustrationForMeanings(meanings: LocalizedText[] | undefined): string | undefined {
  if (!meanings) return undefined;
  for (const meaning of meanings) {
    if (!meaning.en) continue;
    const whole = normalize(meaning.en);
    const direct = findInPhrase(whole);
    if (direct) return direct;

    const parts = meaning.en.split(/[,;/]| or | and /i);
    for (const part of parts) {
      const found = findInPhrase(normalize(part));
      if (found) return found;
    }
  }
  return undefined;
}
